--
-- PostgreSQL database dump
--

\restrict VjCeyRgBvpzHPoKiSEP1AdFrZQgT5xBignn0LrNJvE9JIya1O1npHxXcJLthEpZ

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


--
-- Name: publictenant; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA publictenant;


ALTER SCHEMA publictenant OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone_number character varying(15),
    is_verified boolean NOT NULL,
    avatar character varying(100),
    last_login_ip inet,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: axes_accessattempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.axes_accessattempt (
    id integer NOT NULL,
    user_agent character varying(255) NOT NULL,
    ip_address inet,
    username character varying(255),
    http_accept character varying(1025) NOT NULL,
    path_info character varying(255) NOT NULL,
    attempt_time timestamp with time zone NOT NULL,
    get_data text NOT NULL,
    post_data text NOT NULL,
    failures_since_start integer NOT NULL,
    CONSTRAINT axes_accessattempt_failures_since_start_check CHECK ((failures_since_start >= 0))
);


ALTER TABLE public.axes_accessattempt OWNER TO postgres;

--
-- Name: axes_accessattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.axes_accessattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.axes_accessattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: axes_accessattemptexpiration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.axes_accessattemptexpiration (
    access_attempt_id integer NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.axes_accessattemptexpiration OWNER TO postgres;

--
-- Name: axes_accessfailurelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.axes_accessfailurelog (
    id integer NOT NULL,
    user_agent character varying(255) NOT NULL,
    ip_address inet,
    username character varying(255),
    http_accept character varying(1025) NOT NULL,
    path_info character varying(255) NOT NULL,
    attempt_time timestamp with time zone NOT NULL,
    locked_out boolean NOT NULL
);


ALTER TABLE public.axes_accessfailurelog OWNER TO postgres;

--
-- Name: axes_accessfailurelog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.axes_accessfailurelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.axes_accessfailurelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: axes_accesslog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.axes_accesslog (
    id integer NOT NULL,
    user_agent character varying(255) NOT NULL,
    ip_address inet,
    username character varying(255),
    http_accept character varying(1025) NOT NULL,
    path_info character varying(255) NOT NULL,
    attempt_time timestamp with time zone NOT NULL,
    logout_time timestamp with time zone,
    session_hash character varying(64) NOT NULL
);


ALTER TABLE public.axes_accesslog OWNER TO postgres;

--
-- Name: axes_accesslog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.axes_accesslog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.axes_accesslog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_chordcounter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_chordcounter (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    sub_tasks text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_count_check CHECK ((count >= 0))
);


ALTER TABLE public.django_celery_results_chordcounter OWNER TO postgres;

--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_chordcounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_groupresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_groupresult (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text
);


ALTER TABLE public.django_celery_results_groupresult OWNER TO postgres;

--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_groupresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_taskresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_taskresult (
    id integer NOT NULL,
    task_id character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text,
    date_done timestamp with time zone NOT NULL,
    traceback text,
    meta text,
    task_args text,
    task_kwargs text,
    task_name character varying(255),
    worker character varying(100),
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255),
    date_started timestamp with time zone
);


ALTER TABLE public.django_celery_results_taskresult OWNER TO postgres;

--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_taskresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: monitoring_activitylog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monitoring_activitylog (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.monitoring_activitylog OWNER TO postgres;

--
-- Name: monitoring_activitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.monitoring_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitoring_activitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_client (
    id bigint NOT NULL,
    schema_name character varying(63) NOT NULL,
    name character varying(100) NOT NULL,
    paid_until date,
    on_trial boolean NOT NULL,
    created_on date NOT NULL
);


ALTER TABLE public.orders_client OWNER TO postgres;

--
-- Name: orders_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_domain; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_domain (
    id bigint NOT NULL,
    domain character varying(253) NOT NULL,
    is_primary boolean NOT NULL,
    tenant_id bigint NOT NULL
);


ALTER TABLE public.orders_domain OWNER TO postgres;

--
-- Name: orders_domain_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_domain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_domain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) CONSTRAINT token_blacklist_outstandingtoken_jti_hex_not_null NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: publictenant; Owner: postgres
--

CREATE TABLE publictenant.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE publictenant.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: publictenant; Owner: postgres
--

ALTER TABLE publictenant.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME publictenant.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone_number, is_verified, avatar, last_login_ip, created_at, updated_at) FROM stdin;
2	pbkdf2_sha256$1200000$ncxZak0ktxyGc6Y5gkQgq0$j5t3X202p+79kPdbmvKXgwAJoNtIOK/MykeaTo0IxnI=	\N	f	user2				f	t	2026-07-16 13:08:55.61384+00	\N	f		\N	2026-07-16 13:08:55.786976+00	2026-07-16 13:08:55.786983+00
3	pbkdf2_sha256$1200000$ye61mmIkHRvI4XXcAffa0P$oAvO2tHB20mOHoIo9cH85EcqUj0pvzT5Db2xH39l5XI=	\N	f	user3				f	t	2026-07-16 14:14:49.84842+00	\N	f		\N	2026-07-16 14:14:50.042602+00	2026-07-16 14:14:50.04261+00
4	pbkdf2_sha256$1200000$TEiE1Pf6qQJ3byhtDGat00$4GakbiR6co5A9XM55LrReNUOaHoCBAzo+A+ahm9KvUU=	\N	f	user4			user4@gmail.com	f	t	2026-07-16 16:26:49.983215+00	9876543210	f		\N	2026-07-16 16:26:50.141143+00	2026-07-16 16:26:50.14115+00
5	pbkdf2_sha256$1200000$mDGEktuRk8jaq7qiucXSaN$23YzaWMRTbZdadmbQRduryxWwbNiteUqg/Yt9PLBWHI=	\N	f	user5	Shankar Kumar	B	newuser5@gmail.com	f	t	2026-07-16 16:46:18.591542+00	9999999999	f		\N	2026-07-16 16:46:18.87358+00	2026-07-16 17:11:50.354709+00
6	pbkdf2_sha256$1200000$vz2xNH1pcrEX0bLk3wXgEJ$kXvEeojq7+dGC7eiCBoKf1BhcoQEPyjVjyJUPmsu4Tk=	\N	f	user6				f	t	2026-07-17 11:31:46.21645+00	\N	f		\N	2026-07-17 11:31:46.381102+00	2026-07-17 11:31:46.381109+00
7	pbkdf2_sha256$1200000$on9x4G31XjcUKLZzHYB9sn$JjNkUQPZCLhD6vGMBsFQAbMGZqN9HIMVp35dPhFxUTE=	\N	f	user7				f	t	2026-07-17 12:12:02.433742+00	\N	f		\N	2026-07-17 12:12:02.616505+00	2026-07-17 12:12:02.616509+00
8	pbkdf2_sha256$1200000$QrPBXAd3VWCCve1ObWrnbR$FfoWxN0Zi/P7Pv06JQm8UITVCpge8I3DQh9Q4/Rkqkc=	\N	f	user9	Shankar	B	user9@example.com	f	t	2026-07-17 14:54:27.747371+00	9876543210	f		\N	2026-07-17 14:54:27.899931+00	2026-07-17 15:25:29.385627+00
9	pbkdf2_sha256$1200000$f2ZVuDB5WAJ0pc62fbScFz$kUoS4upwPk84DppD193kR2Yl8PGv++l/xyusibsXdzA=	\N	f	user10	Shankar	B	user10@example.com	f	t	2026-07-17 17:12:54.326407+00	9876543210	f		\N	2026-07-17 17:12:54.503424+00	2026-07-17 17:30:45.012858+00
10	pbkdf2_sha256$1200000$GxzPCn7NQU6mPeOMdQLGWV$tUZgPcP7LFYMxeJ1wYxkazZr/jZEobOmXOSbXaQJfTY=	\N	f	user11	Shankar	B	user11@example.com	f	t	2026-07-17 17:33:47.45674+00	9876543210	f		\N	2026-07-17 17:33:47.628473+00	2026-07-17 17:38:54.833842+00
11	pbkdf2_sha256$1200000$ZohA6gzmwKkUninzC3w3HW$Il29FzV5cqrsfQKIUWfl4gtlprMZ9JBP63+Kkc0nyyI=	\N	f	user12				f	t	2026-07-18 05:43:17.903201+00	\N	f		\N	2026-07-18 05:43:18.054567+00	2026-07-18 05:43:18.054574+00
13	pbkdf2_sha256$1200000$HCcfNMvuPu1xmoBTpihODt$gfBD3h52Cu4Ju2WJAhLdNX4vQflJQHVONEzd8HR7cHY=	\N	f	user20				f	t	2026-07-18 06:19:48.071049+00	\N	f		\N	2026-07-18 06:19:48.233579+00	2026-07-18 06:19:48.233586+00
12	pbkdf2_sha256$1200000$5yDNrlXxHjHo7akakebBLx$0rL+I3ED2ciJDExvJhHqFI42DSOA+rRcHz8iuJzCLo4=	\N	f	Ramesh	Ramesh	C	ramesh13@gmail.com	f	t	2026-07-18 05:51:51+00	9666666666	f	avatars/2013-09-09_21.16.45.jpg	\N	2026-07-18 05:51:51.847155+00	2026-07-21 13:01:38.584233+00
1	pbkdf2_sha256$1200000$sfm6lkGGqWyYbZCclmqVSF$2NZFpoKigpasIvSKXRjP5Z93sEIDjwY/6PrHWYZboCI=	2026-08-16 13:40:22.797188+00	t	djangoprod			djangoprod@gmail.com	t	t	2026-07-10 07:22:11.325439+00	\N	f		\N	2026-07-10 07:22:16.605188+00	2026-07-10 07:22:16.605251+00
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add client	1	add_client
2	Can change client	1	change_client
3	Can delete client	1	delete_client
4	Can view client	1	view_client
5	Can add domain	2	add_domain
6	Can change domain	2	change_domain
7	Can delete domain	2	delete_domain
8	Can view domain	2	view_domain
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add log entry	4	add_logentry
14	Can change log entry	4	change_logentry
15	Can delete log entry	4	delete_logentry
16	Can view log entry	4	view_logentry
17	Can add permission	6	add_permission
18	Can change permission	6	change_permission
19	Can delete permission	6	delete_permission
20	Can view permission	6	view_permission
21	Can add group	5	add_group
22	Can change group	5	change_group
23	Can delete group	5	delete_group
24	Can view group	5	view_group
25	Can add content type	7	add_contenttype
26	Can change content type	7	change_contenttype
27	Can delete content type	7	delete_contenttype
28	Can view content type	7	view_contenttype
29	Can add session	8	add_session
30	Can change session	8	change_session
31	Can delete session	8	delete_session
32	Can view session	8	view_session
33	Can add Blacklisted Token	9	add_blacklistedtoken
34	Can change Blacklisted Token	9	change_blacklistedtoken
35	Can delete Blacklisted Token	9	delete_blacklistedtoken
36	Can view Blacklisted Token	9	view_blacklistedtoken
37	Can add Outstanding Token	10	add_outstandingtoken
38	Can change Outstanding Token	10	change_outstandingtoken
39	Can delete Outstanding Token	10	delete_outstandingtoken
40	Can view Outstanding Token	10	view_outstandingtoken
41	Can add task result	13	add_taskresult
42	Can change task result	13	change_taskresult
43	Can delete task result	13	delete_taskresult
44	Can view task result	13	view_taskresult
45	Can add chord counter	11	add_chordcounter
46	Can change chord counter	11	change_chordcounter
47	Can delete chord counter	11	delete_chordcounter
48	Can view chord counter	11	view_chordcounter
49	Can add group result	12	add_groupresult
50	Can change group result	12	change_groupresult
51	Can delete group result	12	delete_groupresult
52	Can view group result	12	view_groupresult
53	Can add crontab	15	add_crontabschedule
54	Can change crontab	15	change_crontabschedule
55	Can delete crontab	15	delete_crontabschedule
56	Can view crontab	15	view_crontabschedule
57	Can add interval	16	add_intervalschedule
58	Can change interval	16	change_intervalschedule
59	Can delete interval	16	delete_intervalschedule
60	Can view interval	16	view_intervalschedule
61	Can add periodic task	17	add_periodictask
62	Can change periodic task	17	change_periodictask
63	Can delete periodic task	17	delete_periodictask
64	Can view periodic task	17	view_periodictask
65	Can add periodic task track	18	add_periodictasks
66	Can change periodic task track	18	change_periodictasks
67	Can delete periodic task track	18	delete_periodictasks
68	Can view periodic task track	18	view_periodictasks
69	Can add solar event	19	add_solarschedule
70	Can change solar event	19	change_solarschedule
71	Can delete solar event	19	delete_solarschedule
72	Can view solar event	19	view_solarschedule
73	Can add clocked	14	add_clockedschedule
74	Can change clocked	14	change_clockedschedule
75	Can delete clocked	14	delete_clockedschedule
76	Can view clocked	14	view_clockedschedule
77	Can add access attempt	20	add_accessattempt
78	Can change access attempt	20	change_accessattempt
79	Can delete access attempt	20	delete_accessattempt
80	Can view access attempt	20	view_accessattempt
81	Can add access log	23	add_accesslog
82	Can change access log	23	change_accesslog
83	Can delete access log	23	delete_accesslog
84	Can view access log	23	view_accesslog
85	Can add access failure	22	add_accessfailurelog
86	Can change access failure	22	change_accessfailurelog
87	Can delete access failure	22	delete_accessfailurelog
88	Can view access failure	22	view_accessfailurelog
89	Can add access attempt expiration	21	add_accessattemptexpiration
90	Can change access attempt expiration	21	change_accessattemptexpiration
91	Can delete access attempt expiration	21	delete_accessattemptexpiration
92	Can view access attempt expiration	21	view_accessattemptexpiration
93	Can add activity log	24	add_activitylog
94	Can change activity log	24	change_activitylog
95	Can delete activity log	24	delete_activitylog
96	Can view activity log	24	view_activitylog
\.


--
-- Data for Name: axes_accessattempt; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.axes_accessattempt (id, user_agent, ip_address, username, http_accept, path_info, attempt_time, get_data, post_data, failures_since_start) FROM stdin;
3	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36	100.64.0.7	prod1	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7	/admin/login/	2026-08-16 13:40:05.244709+00	next=/admin/	csrfmiddlewaretoken=dG8h5799cOQZI5mGewOwGlq2mFswcnWtGB17u2hBLva9ooDMc7T7IFJdNvOg2vMv\nusername=********************\npassword=********************\nnext=/admin/	1
\.


--
-- Data for Name: axes_accessattemptexpiration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.axes_accessattemptexpiration (access_attempt_id, expires_at) FROM stdin;
\.


--
-- Data for Name: axes_accessfailurelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.axes_accessfailurelog (id, user_agent, ip_address, username, http_accept, path_info, attempt_time, locked_out) FROM stdin;
\.


--
-- Data for Name: axes_accesslog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.axes_accesslog (id, user_agent, ip_address, username, http_accept, path_info, attempt_time, logout_time, session_hash) FROM stdin;
1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36	100.64.0.11	djangoprod	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7	/admin/login/	2026-07-10 08:20:22.198701+00	\N	1b609093d9da737a4438a6dec23adab5d8828c527918ade04441eb84bf8d7016
2	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36	100.64.0.9	djangoprod	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7	/admin/login/	2026-07-24 10:57:54.459196+00	\N	4352c21b7a9395981b96d725014ca700356a075ef5406aa08b6e4372db89683f
3	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36	100.64.0.6	djangoprod	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7	/admin/login/	2026-08-16 13:40:22.790678+00	\N	130bf98e08f58aacec546ae6da4e60b162b24a98e832a13744afbcc198598b59
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-07-21 13:01:38.616747+00	12	Ramesh	2	[{"changed": {"fields": ["Avatar"]}}]	3	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_celery_results_chordcounter; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_chordcounter (id, group_id, sub_tasks, count) FROM stdin;
\.


--
-- Data for Name: django_celery_results_groupresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_groupresult (id, group_id, date_created, date_done, content_type, content_encoding, result) FROM stdin;
\.


--
-- Data for Name: django_celery_results_taskresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_taskresult (id, task_id, status, content_type, content_encoding, result, date_done, traceback, meta, task_args, task_kwargs, task_name, worker, date_created, periodic_task_name, date_started) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	orders	client
2	orders	domain
3	accounts	user
4	admin	logentry
5	auth	group
6	auth	permission
7	contenttypes	contenttype
8	sessions	session
9	token_blacklist	blacklistedtoken
10	token_blacklist	outstandingtoken
11	django_celery_results	chordcounter
12	django_celery_results	groupresult
13	django_celery_results	taskresult
14	django_celery_beat	clockedschedule
15	django_celery_beat	crontabschedule
16	django_celery_beat	intervalschedule
17	django_celery_beat	periodictask
18	django_celery_beat	periodictasks
19	django_celery_beat	solarschedule
20	axes	accessattempt
21	axes	accessattemptexpiration
22	axes	accessfailurelog
23	axes	accesslog
24	monitoring	activitylog
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-10 07:07:48.08384+00
2	contenttypes	0002_remove_content_type_name	2026-07-10 07:07:50.514134+00
3	auth	0001_initial	2026-07-10 07:07:57.560669+00
4	auth	0002_alter_permission_name_max_length	2026-07-10 07:07:59.00952+00
5	auth	0003_alter_user_email_max_length	2026-07-10 07:07:59.747623+00
6	auth	0004_alter_user_username_opts	2026-07-10 07:08:00.717828+00
7	auth	0005_alter_user_last_login_null	2026-07-10 07:08:01.73381+00
8	auth	0006_require_contenttypes_0002	2026-07-10 07:08:02.701284+00
9	auth	0007_alter_validators_add_error_messages	2026-07-10 07:08:03.697055+00
10	auth	0008_alter_user_username_max_length	2026-07-10 07:08:04.734321+00
11	auth	0009_alter_user_last_name_max_length	2026-07-10 07:08:05.74566+00
12	auth	0010_alter_group_name_max_length	2026-07-10 07:08:07.676937+00
13	auth	0011_update_proxy_permissions	2026-07-10 07:08:08.414374+00
14	auth	0012_alter_user_first_name_max_length	2026-07-10 07:08:09.412749+00
15	accounts	0001_initial	2026-07-10 07:08:17.637147+00
16	admin	0001_initial	2026-07-10 07:08:21.046981+00
17	admin	0002_logentry_remove_auto_add	2026-07-10 07:08:21.639763+00
18	admin	0003_logentry_add_action_flag_choices	2026-07-10 07:08:22.663343+00
19	axes	0001_initial	2026-07-10 07:08:24.860645+00
20	axes	0002_auto_20151217_2044	2026-07-10 07:08:34.801861+00
21	axes	0003_auto_20160322_0929	2026-07-10 07:08:35.643496+00
22	axes	0004_auto_20181024_1538	2026-07-10 07:08:36.698938+00
23	axes	0005_remove_accessattempt_trusted	2026-07-10 07:08:38.698183+00
24	axes	0006_remove_accesslog_trusted	2026-07-10 07:08:40.433437+00
25	axes	0007_alter_accessattempt_unique_together	2026-07-10 07:08:42.762982+00
26	axes	0008_accessfailurelog	2026-07-10 07:08:46.867469+00
27	axes	0009_add_session_hash	2026-07-10 07:08:49.096208+00
28	axes	0010_accessattemptexpiration	2026-07-10 07:08:51.304151+00
29	django_celery_beat	0001_initial	2026-07-10 07:08:56.703867+00
30	django_celery_beat	0002_auto_20161118_0346	2026-07-10 07:08:59.134155+00
31	django_celery_beat	0003_auto_20161209_0049	2026-07-10 07:09:00.596461+00
32	django_celery_beat	0004_auto_20170221_0000	2026-07-10 07:09:01.334113+00
33	django_celery_beat	0005_add_solarschedule_events_choices	2026-07-10 07:09:02.310999+00
34	django_celery_beat	0006_auto_20180322_0932	2026-07-10 07:09:07.350732+00
35	django_celery_beat	0007_auto_20180521_0826	2026-07-10 07:09:10.63612+00
36	django_celery_beat	0008_auto_20180914_1922	2026-07-10 07:09:11.630346+00
37	django_celery_beat	0006_auto_20180210_1226	2026-07-10 07:09:12.750252+00
38	django_celery_beat	0006_periodictask_priority	2026-07-10 07:09:14.485389+00
39	django_celery_beat	0009_periodictask_headers	2026-07-10 07:09:16.917824+00
40	django_celery_beat	0010_auto_20190429_0326	2026-07-10 07:09:19.160345+00
41	django_celery_beat	0011_auto_20190508_0153	2026-07-10 07:09:22.017991+00
42	django_celery_beat	0012_periodictask_expire_seconds	2026-07-10 07:09:23.261666+00
43	django_celery_beat	0013_auto_20200609_0727	2026-07-10 07:09:24.066902+00
44	django_celery_beat	0014_remove_clockedschedule_enabled	2026-07-10 07:09:25.960773+00
45	django_celery_beat	0015_edit_solarschedule_events_choices	2026-07-10 07:09:26.69786+00
46	django_celery_beat	0016_alter_crontabschedule_timezone	2026-07-10 07:09:27.73976+00
47	django_celery_beat	0017_alter_crontabschedule_month_of_year	2026-07-10 07:09:28.772737+00
48	django_celery_beat	0018_improve_crontab_helptext	2026-07-10 07:09:29.765566+00
49	django_celery_beat	0019_alter_periodictasks_options	2026-07-10 07:09:30.712584+00
50	django_celery_results	0001_initial	2026-07-10 07:09:33.564619+00
51	django_celery_results	0002_add_task_name_args_kwargs	2026-07-10 07:09:35.727415+00
52	django_celery_results	0003_auto_20181106_1101	2026-07-10 07:09:36.451017+00
53	django_celery_results	0004_auto_20190516_0412	2026-07-10 07:09:41.24808+00
54	django_celery_results	0005_taskresult_worker	2026-07-10 07:09:43.864776+00
55	django_celery_results	0006_taskresult_date_created	2026-07-10 07:09:47.282237+00
56	django_celery_results	0007_remove_taskresult_hidden	2026-07-10 07:09:48.744165+00
57	django_celery_results	0008_chordcounter	2026-07-10 07:09:50.905336+00
58	django_celery_results	0009_groupresult	2026-07-10 07:10:09.097079+00
59	django_celery_results	0010_remove_duplicate_indices	2026-07-10 07:10:11.976078+00
60	django_celery_results	0011_taskresult_periodic_task_name	2026-07-10 07:10:13.401301+00
61	django_celery_results	0012_taskresult_date_started	2026-07-10 07:10:14.818998+00
62	django_celery_results	0013_taskresult_django_cele_periodi_1993cf_idx	2026-07-10 07:10:16.226251+00
63	django_celery_results	0014_alter_taskresult_status	2026-07-10 07:10:16.95717+00
65	orders	0001_initial	2026-07-10 07:10:22.691832+00
66	sessions	0001_initial	2026-07-10 07:10:25.06794+00
67	token_blacklist	0001_initial	2026-07-10 07:10:28.489884+00
68	token_blacklist	0002_outstandingtoken_jti_hex	2026-07-10 07:10:29.757472+00
69	token_blacklist	0003_auto_20171017_2007	2026-07-10 07:10:31.297022+00
70	token_blacklist	0004_auto_20171017_2013	2026-07-10 07:10:34.336616+00
71	token_blacklist	0005_remove_outstandingtoken_jti	2026-07-10 07:10:35.99862+00
72	token_blacklist	0006_auto_20171017_2113	2026-07-10 07:10:37.666238+00
73	token_blacklist	0007_auto_20171017_2214	2026-07-10 07:10:42.809823+00
74	token_blacklist	0008_migrate_to_bigautofield	2026-07-10 07:10:52.259839+00
75	token_blacklist	0010_fix_migrate_to_bigautofield	2026-07-10 07:10:53.045575+00
76	token_blacklist	0011_linearizes_history	2026-07-10 07:10:53.960212+00
77	token_blacklist	0012_alter_outstandingtoken_user	2026-07-10 07:10:54.948686+00
78	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-07-10 07:10:55.948+00
80	monitoring	0001_initial	2026-07-16 13:57:30.947548+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: monitoring_activitylog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.monitoring_activitylog (id, action, metadata, created_at, user_id) FROM stdin;
1	register	{}	2026-07-16 14:14:50.054621+00	3
2	login	{}	2026-07-16 14:27:39.974834+00	3
3	login	{}	2026-07-16 15:14:32.334384+00	3
4	login	{}	2026-07-16 16:15:10.964076+00	3
5	register	{}	2026-07-16 16:26:50.150883+00	4
6	register	{}	2026-07-16 16:46:19.128305+00	5
7	login	{}	2026-07-16 16:46:52.623489+00	5
8	login	{}	2026-07-16 17:10:44.46686+00	5
9	register	{}	2026-07-17 11:31:46.395506+00	6
10	register	{}	2026-07-17 12:12:02.626649+00	7
11	login	{}	2026-07-17 12:14:23.017157+00	7
12	register	{}	2026-07-17 14:54:27.909319+00	8
13	login	{}	2026-07-17 15:02:27.753916+00	8
14	login	{}	2026-07-17 15:19:56.363414+00	8
15	login	{}	2026-07-17 15:21:47.15624+00	8
16	login	{}	2026-07-17 15:23:05.39968+00	8
17	register	{}	2026-07-17 17:12:54.51658+00	9
18	login	{}	2026-07-17 17:21:09.199179+00	9
19	register	{}	2026-07-17 17:33:47.63887+00	10
20	login	{}	2026-07-17 17:37:12.295382+00	10
21	register	{}	2026-07-18 05:43:18.066138+00	11
22	login	{}	2026-07-18 05:47:06.740731+00	11
23	register	{}	2026-07-18 05:51:51.858482+00	12
24	login	{}	2026-07-18 05:52:40.373748+00	12
25	logout	{}	2026-07-18 06:00:49.763532+00	12
26	register	{}	2026-07-18 06:19:48.245374+00	13
\.


--
-- Data for Name: orders_client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_client (id, schema_name, name, paid_until, on_trial, created_on) FROM stdin;
1	public	Public Tenant	\N	f	2026-07-10
\.


--
-- Data for Name: orders_domain; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_domain (id, domain, is_primary, tenant_id) FROM stdin;
1	localhost	f	1
2	gregarious-purpose-production-98d4.up.railway.app	t	1
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-07-18 06:00:49.748176+00	14
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDI5ODQ1OSwiaWF0IjoxNzg0MjEyMDU5LCJqdGkiOiIxZDQ1MjczNzJlYTE0ZjI3YjMxNTg1ZWUxZWM2YzQ2ZCIsInVzZXJfaWQiOiIzIn0.OtzhzoQz4TPkNxgHWvXEfEc0yDNwfXCfWKCI57fputc	2026-07-16 14:27:39.83594+00	2026-07-17 14:27:39+00	3	1d4527372ea14f27b31585ee1ec6c46d
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDMwMTI3MiwiaWF0IjoxNzg0MjE0ODcyLCJqdGkiOiI4ZmFmOTEzNGM2YTk0ODY5OTc3NWI4NWY3M2I5NTRjNyIsInVzZXJfaWQiOiIzIn0.8_snPbi8uLWQYue5wEOIDtNgoqGGEjwtKCK2psS5YAc	2026-07-16 15:14:32.292112+00	2026-07-17 15:14:32+00	3	8faf9134c6a948699775b85f73b954c7
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDgyMzMxMCwiaWF0IjoxNzg0MjE4NTEwLCJqdGkiOiI4YTc1MzJkODNiNDk0MTIwOGMxOGQ2OTNlYmZlZWFlMCIsInVzZXJfaWQiOiIzIn0.MZxYuy_6xdhGPvkJahIg0Jpr2VxVe2H5z1S-FBtKYLA	2026-07-16 16:15:10.913825+00	2026-07-23 16:15:10+00	3	8a7532d83b4941208c18d693ebfeeae0
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDgyNTIxMSwiaWF0IjoxNzg0MjIwNDExLCJqdGkiOiJhZTc3NGJlYjRjYmQ0MTJlYjBhMDVlZDcwNzQzYjk1YyIsInVzZXJfaWQiOiI1In0.TQi-YLCiPszOuYucLZfoZWL4Tj0g-nKlTkAe_OktNWU	2026-07-16 16:46:51.967196+00	2026-07-23 16:46:51+00	5	ae774beb4cbd412eb0a05ed70743b95c
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDgyNjY0NCwiaWF0IjoxNzg0MjIxODQ0LCJqdGkiOiI1ZWQ4Y2QwZWU4NzQ0Y2NkOWZkMjhjY2ZjOWFmMjQ1ZCIsInVzZXJfaWQiOiI1In0.fLIC1hdPpVEdglNzf0acfBL6Dld9lyZMQATJiESpiVY	2026-07-16 17:10:44.428427+00	2026-07-23 17:10:44+00	5	5ed8cd0ee8744ccd9fd28ccfc9af245d
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDg5NTI2MiwiaWF0IjoxNzg0MjkwNDYyLCJqdGkiOiIzOGRlNWJhNTY5NGE0ZmU4OTRjM2RkN2EzOGQzODVjOSIsInVzZXJfaWQiOiI3In0.UX_JMkA55KMXFOmzjU9drN_AlYqvmkLWAj7PToWELnQ	2026-07-17 12:14:22.961532+00	2026-07-24 12:14:22+00	7	38de5ba5694a4fe894c3dd7a38d385c9
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkwNTM0NywiaWF0IjoxNzg0MzAwNTQ3LCJqdGkiOiIwYTNlYjdmYWRmMGY0ZWJhYjkyYWM5NTUzNTcwYjhkMCIsInVzZXJfaWQiOiI4In0.HRjWStOPhY3xtsP5ww8FZh7jZ5Dw6KIGOQl9yXhNW7g	2026-07-17 15:02:27.311363+00	2026-07-24 15:02:27+00	8	0a3eb7fadf0f4ebab92ac9553570b8d0
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkwNjM5NiwiaWF0IjoxNzg0MzAxNTk2LCJqdGkiOiI5YTRlNjkyZDc5ZDQ0YTQ3YTE4YjRiZTEzMzExMzU1OSIsInVzZXJfaWQiOiI4In0.Z8dsYrmjQbAiWVfU0Agpk5z0k1vWIIqJIn7l2zwFxqk	2026-07-17 15:19:56.330831+00	2026-07-24 15:19:56+00	8	9a4e692d79d44a47a18b4be133113559
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkwNjUwNywiaWF0IjoxNzg0MzAxNzA3LCJqdGkiOiI4YjkzNzMyMDJkYTk0ZDZlYjk3ZGZiYTFmNmQzNDcxYSIsInVzZXJfaWQiOiI4In0.3xQM563fLtmjErOOhHEAJRAnYiJXu8fDYyNVkXxHoZU	2026-07-17 15:21:47.138839+00	2026-07-24 15:21:47+00	8	8b9373202da94d6eb97dfba1f6d3471a
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkwNjU4NSwiaWF0IjoxNzg0MzAxNzg1LCJqdGkiOiJmMDQzZmZmNTkwMzA0NGZkYjNhN2U5MmQ5MGY3MGM5OSIsInVzZXJfaWQiOiI4In0.UoukN6dZNLU7o7PaCX8TpbcG1Y2dDEF0po5rP5TSNUc	2026-07-17 15:23:05.382618+00	2026-07-24 15:23:05+00	8	f043fff5903044fdb3a7e92d90f70c99
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkxMzY2OSwiaWF0IjoxNzg0MzA4ODY5LCJqdGkiOiI3YTMzYjA1ZjBjNjc0ZGIxYmUzZDM1YjhkYzJhYzZjMSIsInVzZXJfaWQiOiI5In0.e_JZrZekK044KfxM4MEu1GjiymsAv12z-BK2Noo_G_I	2026-07-17 17:21:09.167095+00	2026-07-24 17:21:09+00	9	7a33b05f0c674db1be3d35b8dc2ac6c1
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDkxNDYzMiwiaWF0IjoxNzg0MzA5ODMyLCJqdGkiOiJhOWEwYWExMTNiOWQ0NDI3YWQ2NDI2MDMyNjkxZDUwNSIsInVzZXJfaWQiOiIxMCJ9.m0ymLJjjWbxjK2dYTIH1LCSonZcOp_s3tdM-VSd3xQo	2026-07-17 17:37:12.264939+00	2026-07-24 17:37:12+00	10	a9a0aa113b9d4427ad6426032691d505
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDk1ODQyNiwiaWF0IjoxNzg0MzUzNjI2LCJqdGkiOiIyMTc5ZjE5NjViNjk0MDgwYWQwOTgxMzJiMWY2YWZmMyIsInVzZXJfaWQiOiIxMSJ9.-xFAbbCqRJnmUEGJZ-vwNtF0eKzSXlL97Qw21baRGJ4	2026-07-18 05:47:06.621008+00	2026-07-25 05:47:06+00	11	2179f1965b694080ad098132b1f6aff3
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDk1ODc2MCwiaWF0IjoxNzg0MzUzOTYwLCJqdGkiOiIxMjdiYTVjY2IyN2E0YzEyOWMxY2Q1NWNjNzY5MTM1YyIsInVzZXJfaWQiOiIxMiJ9.xIVa30GIocbY88Oz-voWHjwGxktsNfObLllng-hXbfg	2026-07-18 05:52:40.343793+00	2026-07-25 05:52:40+00	12	127ba5ccb27a4c129c1cd55cc769135c
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: publictenant; Owner: postgres
--

COPY publictenant.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-21 08:01:49.665625+00
2	auth	0001_initial	2026-05-21 08:01:50.688506+00
3	admin	0001_initial	2026-05-21 08:01:51.660923+00
4	admin	0002_logentry_remove_auto_add	2026-05-21 08:01:52.654232+00
5	admin	0003_logentry_add_action_flag_choices	2026-05-21 08:01:53.633741+00
6	contenttypes	0002_remove_content_type_name	2026-05-21 08:01:54.613226+00
7	auth	0002_alter_permission_name_max_length	2026-05-21 08:01:55.619525+00
8	auth	0003_alter_user_email_max_length	2026-05-21 08:01:56.601363+00
9	auth	0004_alter_user_username_opts	2026-05-21 08:01:57.571711+00
10	auth	0005_alter_user_last_login_null	2026-05-21 08:01:58.549963+00
11	auth	0006_require_contenttypes_0002	2026-05-21 08:01:59.471749+00
12	auth	0007_alter_validators_add_error_messages	2026-05-21 08:02:00.457686+00
13	auth	0008_alter_user_username_max_length	2026-05-21 08:02:01.444712+00
14	auth	0009_alter_user_last_name_max_length	2026-05-21 08:02:02.384187+00
15	auth	0010_alter_group_name_max_length	2026-05-21 08:02:03.369927+00
16	auth	0011_update_proxy_permissions	2026-05-21 08:02:04.28456+00
17	auth	0012_alter_user_first_name_max_length	2026-05-21 08:02:05.272965+00
18	axes	0001_initial	2026-05-21 08:02:06.210632+00
19	axes	0002_auto_20151217_2044	2026-05-21 08:02:07.205863+00
20	axes	0003_auto_20160322_0929	2026-05-21 08:02:08.231543+00
21	axes	0004_auto_20181024_1538	2026-05-21 08:02:09.285908+00
22	axes	0005_remove_accessattempt_trusted	2026-05-21 08:02:10.235309+00
23	axes	0006_remove_accesslog_trusted	2026-05-21 08:02:11.171344+00
24	axes	0007_alter_accessattempt_unique_together	2026-05-21 08:02:12.115068+00
25	axes	0008_accessfailurelog	2026-05-21 08:02:13.038818+00
26	axes	0009_add_session_hash	2026-05-21 08:02:13.963249+00
27	axes	0010_accessattemptexpiration	2026-05-21 08:02:14.913178+00
28	django_celery_beat	0001_initial	2026-05-21 08:02:15.881749+00
29	django_celery_beat	0002_auto_20161118_0346	2026-05-21 08:02:16.848875+00
30	django_celery_beat	0003_auto_20161209_0049	2026-05-21 08:02:17.83898+00
31	django_celery_beat	0004_auto_20170221_0000	2026-05-21 08:02:18.784276+00
32	django_celery_beat	0005_add_solarschedule_events_choices	2026-05-21 08:02:19.723462+00
33	django_celery_beat	0006_auto_20180322_0932	2026-05-21 08:02:20.855014+00
34	django_celery_beat	0007_auto_20180521_0826	2026-05-21 08:02:21.956323+00
35	django_celery_beat	0008_auto_20180914_1922	2026-05-21 08:02:23.075981+00
36	django_celery_beat	0006_auto_20180210_1226	2026-05-21 08:02:24.137102+00
37	django_celery_beat	0006_periodictask_priority	2026-05-21 08:02:25.146169+00
38	django_celery_beat	0009_periodictask_headers	2026-05-21 08:02:26.173999+00
39	django_celery_beat	0010_auto_20190429_0326	2026-05-21 08:02:28.835347+00
40	django_celery_beat	0011_auto_20190508_0153	2026-05-21 08:02:29.844585+00
41	django_celery_beat	0012_periodictask_expire_seconds	2026-05-21 08:02:30.862927+00
42	django_celery_beat	0013_auto_20200609_0727	2026-05-21 08:02:31.913839+00
43	django_celery_beat	0014_remove_clockedschedule_enabled	2026-05-21 08:02:32.873676+00
44	django_celery_beat	0015_edit_solarschedule_events_choices	2026-05-21 08:02:33.825118+00
45	django_celery_beat	0016_alter_crontabschedule_timezone	2026-05-21 08:02:34.890258+00
46	django_celery_beat	0017_alter_crontabschedule_month_of_year	2026-05-21 08:02:35.948367+00
47	django_celery_beat	0018_improve_crontab_helptext	2026-05-21 08:02:36.990402+00
48	django_celery_beat	0019_alter_periodictasks_options	2026-05-21 08:02:37.921859+00
49	django_celery_results	0001_initial	2026-05-21 08:02:38.864139+00
50	django_celery_results	0002_add_task_name_args_kwargs	2026-05-21 08:02:39.853803+00
51	django_celery_results	0003_auto_20181106_1101	2026-05-21 08:02:40.78703+00
52	django_celery_results	0004_auto_20190516_0412	2026-05-21 08:02:41.980867+00
53	django_celery_results	0005_taskresult_worker	2026-05-21 08:02:42.905978+00
54	django_celery_results	0006_taskresult_date_created	2026-05-21 08:02:43.844723+00
55	django_celery_results	0007_remove_taskresult_hidden	2026-05-21 08:02:44.784885+00
56	django_celery_results	0008_chordcounter	2026-05-21 08:02:45.704822+00
57	django_celery_results	0009_groupresult	2026-05-21 08:02:46.84755+00
58	django_celery_results	0010_remove_duplicate_indices	2026-05-21 08:02:47.817299+00
59	django_celery_results	0011_taskresult_periodic_task_name	2026-05-21 08:02:48.736798+00
60	django_celery_results	0012_taskresult_date_started	2026-05-21 08:02:49.68377+00
61	django_celery_results	0013_taskresult_django_cele_periodi_1993cf_idx	2026-05-21 08:02:50.623246+00
62	django_celery_results	0014_alter_taskresult_status	2026-05-21 08:02:51.559034+00
63	orders	0001_initial	2026-05-21 08:02:52.513149+00
64	sessions	0001_initial	2026-05-21 08:02:53.436884+00
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 13, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 96, true);


--
-- Name: axes_accessattempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.axes_accessattempt_id_seq', 3, true);


--
-- Name: axes_accessfailurelog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.axes_accessfailurelog_id_seq', 1, false);


--
-- Name: axes_accesslog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.axes_accesslog_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_chordcounter_id_seq', 1, false);


--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_groupresult_id_seq', 1, false);


--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_taskresult_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 24, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 80, true);


--
-- Name: monitoring_activitylog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monitoring_activitylog_id_seq', 26, true);


--
-- Name: orders_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_client_id_seq', 1, true);


--
-- Name: orders_domain_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_domain_id_seq', 2, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: publictenant; Owner: postgres
--

SELECT pg_catalog.setval('publictenant.django_migrations_id_seq', 64, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: axes_accessattempt axes_accessattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accessattempt
    ADD CONSTRAINT axes_accessattempt_pkey PRIMARY KEY (id);


--
-- Name: axes_accessattempt axes_accessattempt_username_ip_address_user_agent_8ea22282_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accessattempt
    ADD CONSTRAINT axes_accessattempt_username_ip_address_user_agent_8ea22282_uniq UNIQUE (username, ip_address, user_agent);


--
-- Name: axes_accessattemptexpiration axes_accessattemptexpiration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accessattemptexpiration
    ADD CONSTRAINT axes_accessattemptexpiration_pkey PRIMARY KEY (access_attempt_id);


--
-- Name: axes_accessfailurelog axes_accessfailurelog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accessfailurelog
    ADD CONSTRAINT axes_accessfailurelog_pkey PRIMARY KEY (id);


--
-- Name: axes_accesslog axes_accesslog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accesslog
    ADD CONSTRAINT axes_accesslog_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_task_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: monitoring_activitylog monitoring_activitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoring_activitylog
    ADD CONSTRAINT monitoring_activitylog_pkey PRIMARY KEY (id);


--
-- Name: orders_client orders_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_client
    ADD CONSTRAINT orders_client_pkey PRIMARY KEY (id);


--
-- Name: orders_client orders_client_schema_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_client
    ADD CONSTRAINT orders_client_schema_name_key UNIQUE (schema_name);


--
-- Name: orders_domain orders_domain_domain_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_domain
    ADD CONSTRAINT orders_domain_domain_key UNIQUE (domain);


--
-- Name: orders_domain orders_domain_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_domain
    ADD CONSTRAINT orders_domain_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: publictenant; Owner: postgres
--

ALTER TABLE ONLY publictenant.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: axes_accessattempt_ip_address_10922d9c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessattempt_ip_address_10922d9c ON public.axes_accessattempt USING btree (ip_address);


--
-- Name: axes_accessattempt_user_agent_ad89678b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessattempt_user_agent_ad89678b ON public.axes_accessattempt USING btree (user_agent);


--
-- Name: axes_accessattempt_user_agent_ad89678b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessattempt_user_agent_ad89678b_like ON public.axes_accessattempt USING btree (user_agent varchar_pattern_ops);


--
-- Name: axes_accessattempt_username_3f2d4ca0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessattempt_username_3f2d4ca0 ON public.axes_accessattempt USING btree (username);


--
-- Name: axes_accessattempt_username_3f2d4ca0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessattempt_username_3f2d4ca0_like ON public.axes_accessattempt USING btree (username varchar_pattern_ops);


--
-- Name: axes_accessfailurelog_ip_address_2e9f5a7f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessfailurelog_ip_address_2e9f5a7f ON public.axes_accessfailurelog USING btree (ip_address);


--
-- Name: axes_accessfailurelog_user_agent_ea145dda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessfailurelog_user_agent_ea145dda ON public.axes_accessfailurelog USING btree (user_agent);


--
-- Name: axes_accessfailurelog_user_agent_ea145dda_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessfailurelog_user_agent_ea145dda_like ON public.axes_accessfailurelog USING btree (user_agent varchar_pattern_ops);


--
-- Name: axes_accessfailurelog_username_a8b7e8a4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessfailurelog_username_a8b7e8a4 ON public.axes_accessfailurelog USING btree (username);


--
-- Name: axes_accessfailurelog_username_a8b7e8a4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accessfailurelog_username_a8b7e8a4_like ON public.axes_accessfailurelog USING btree (username varchar_pattern_ops);


--
-- Name: axes_accesslog_ip_address_86b417e5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accesslog_ip_address_86b417e5 ON public.axes_accesslog USING btree (ip_address);


--
-- Name: axes_accesslog_user_agent_0e659004; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accesslog_user_agent_0e659004 ON public.axes_accesslog USING btree (user_agent);


--
-- Name: axes_accesslog_user_agent_0e659004_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accesslog_user_agent_0e659004_like ON public.axes_accesslog USING btree (user_agent varchar_pattern_ops);


--
-- Name: axes_accesslog_username_df93064b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accesslog_username_df93064b ON public.axes_accesslog USING btree (username);


--
-- Name: axes_accesslog_username_df93064b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX axes_accesslog_username_df93064b_like ON public.axes_accesslog USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cele_date_cr_bd6c1d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_bd6c1d_idx ON public.django_celery_results_groupresult USING btree (date_created);


--
-- Name: django_cele_date_cr_f04a50_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_f04a50_idx ON public.django_celery_results_taskresult USING btree (date_created);


--
-- Name: django_cele_date_do_caae0e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_caae0e_idx ON public.django_celery_results_groupresult USING btree (date_done);


--
-- Name: django_cele_date_do_f59aad_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_f59aad_idx ON public.django_celery_results_taskresult USING btree (date_done);


--
-- Name: django_cele_periodi_1993cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_periodi_1993cf_idx ON public.django_celery_results_taskresult USING btree (periodic_task_name);


--
-- Name: django_cele_status_9b6201_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_status_9b6201_idx ON public.django_celery_results_taskresult USING btree (status);


--
-- Name: django_cele_task_na_08aec9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_task_na_08aec9_idx ON public.django_celery_results_taskresult USING btree (task_name);


--
-- Name: django_cele_worker_d54dd8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_worker_d54dd8_idx ON public.django_celery_results_taskresult USING btree (worker);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_celery_results_chordcounter_group_id_1f70858c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_chordcounter_group_id_1f70858c_like ON public.django_celery_results_chordcounter USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_groupresult_group_id_a085f1a9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_groupresult_group_id_a085f1a9_like ON public.django_celery_results_groupresult USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_taskresult_task_id_de0d95bf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_taskresult_task_id_de0d95bf_like ON public.django_celery_results_taskresult USING btree (task_id varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: monitoring_activitylog_user_id_f7bd31f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX monitoring_activitylog_user_id_f7bd31f7 ON public.monitoring_activitylog USING btree (user_id);


--
-- Name: orders_client_schema_name_b9384d6c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_client_schema_name_b9384d6c_like ON public.orders_client USING btree (schema_name varchar_pattern_ops);


--
-- Name: orders_domain_domain_b49f14be_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_domain_domain_b49f14be_like ON public.orders_domain USING btree (domain varchar_pattern_ops);


--
-- Name: orders_domain_is_primary_269b4c52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_domain_is_primary_269b4c52 ON public.orders_domain USING btree (is_primary);


--
-- Name: orders_domain_tenant_id_1b0c5de2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_domain_tenant_id_1b0c5de2 ON public.orders_domain USING btree (tenant_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: axes_accessattemptexpiration axes_accessattemptex_access_attempt_id_6b73a47a_fk_axes_acce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.axes_accessattemptexpiration
    ADD CONSTRAINT axes_accessattemptex_access_attempt_id_6b73a47a_fk_axes_acce FOREIGN KEY (access_attempt_id) REFERENCES public.axes_accessattempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: monitoring_activitylog monitoring_activitylog_user_id_f7bd31f7_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoring_activitylog
    ADD CONSTRAINT monitoring_activitylog_user_id_f7bd31f7_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_domain orders_domain_tenant_id_1b0c5de2_fk_orders_client_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_domain
    ADD CONSTRAINT orders_domain_tenant_id_1b0c5de2_fk_orders_client_id FOREIGN KEY (tenant_id) REFERENCES public.orders_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict VjCeyRgBvpzHPoKiSEP1AdFrZQgT5xBignn0LrNJvE9JIya1O1npHxXcJLthEpZ

