[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
addopts = --cov=apps --cov-report=xml --cov-report=html --cov-fail-under=75 -v --tb=short

[coverage:run]
source = apps
omit =
    */migrations/*
    */admin.py
    */apps.py
    */manage.py
    */tests/*
    */conftest.py
