# railway.toml
[build]
builder = "dockerfile"
dockerfilePath = "docker/production/Dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "gregarious-purpose"
source = "."

[[services]]
name = "celery-worker"
startCommand = "celery -A config worker -l WARNING --concurrency=4"
