[build]
builder = "dockerfile"
dockerfilePath = "docker/staging/Dockerfile"
watchPatterns = ["**/*.py", "requirements*.txt", "Dockerfile"]

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "charming-passion"
source = "."

[[services]]
name = "celery-worker"
startCommand = "celery -A config worker -l WARNING --concurrency=4"
