# Generated by Django 6.0.8 on 2026-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("student_class", models.CharField(max_length=50)),
                ("joining_date", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("father_name", models.CharField(blank=True, max_length=150)),
                ("mother_name", models.CharField(blank=True, max_length=150)),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Student",
                "verbose_name_plural": "School Students",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("joining_date", models.DateField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("qualification", models.CharField(blank=True, max_length=150)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Teacher",
                "verbose_name_plural": "School Teachers",
                "ordering": ["name"],
            },
        ),
    ]
